// Shading entry point — reads G-buffer, builds ShadingContext, dispatches
// to the appropriate shading model, handles debug visualization modes.
//
// This file is concatenated after shade_common.wgsl and all shading model
// files by the CPU-side ShaderComposer.

// ---------- Shader Dispatch ----------
// GENERATED BY SHADER_COMPOSER — do not edit this function manually.
// The ShaderComposer replaces the SHADER_DISPATCH_PLACEHOLDER marker below
// with a generated switch statement over all registered shading models.

// SHADER_DISPATCH_PLACEHOLDER

// ---------- Entry point ----------

@compute @workgroup_size(8, 8, 1)
fn main(@builtin(global_invocation_id) pixel: vec3<u32>) {
    let dims = vec2<u32>(textureDimensions(hdr_output));
    if pixel.x >= dims.x || pixel.y >= dims.y {
        return;
    }

    let coord = vec2<i32>(pixel.xy);

    // Read G-buffer
    let pos_data = textureLoad(gbuf_position, coord, 0);
    let hit_dist = pos_data.w;

    // Sky pixel — analytic atmosphere or fallback gradient.
    if hit_dist >= MAX_FLOAT * 0.5 {
        var sky: vec3<f32>;
        if shade_uniforms.sky_params.z > 0.5 {
            // Analytic Rayleigh + Mie atmosphere with sun disk.
            let ray_dir = compute_view_ray(pixel.xy, dims);
            sky = atmosphere_sky(ray_dir, normalize(shade_uniforms.sun_dir.xyz));
        } else {
            // Fallback: simple gradient.
            let uv_y = f32(pixel.y) / f32(dims.y);
            sky = mix(SKY_HORIZON, SKY_ZENITH, uv_y);
        }
        textureStore(hdr_output, coord, vec4<f32>(sky, 1.0));
        return;
    }

    let world_pos = pos_data.xyz;
    let normal_data = textureLoad(gbuf_normal, coord, 0);
    var normal = normalize(normal_data.xyz);
    let blend_weight = normal_data.w;

    let packed_mat = textureLoad(gbuf_material, coord, 0).r;
    let material_id = packed_mat & 0xFFu;
    let object_id_bits = (packed_mat >> 24u) & 0xFFu;

    // Resolve material from table (geometry-first: u8 material_id, no blending)
    let resolved = resolve_material_from(materials[material_id]);
    var albedo = resolved.albedo;

    // Per-voxel color modulation (geometry-first: surface voxel RGBA tints albedo)
    if object_id_bits > 0u {
        let color_obj = objects[object_id_bits - 1u];
        if color_obj.sdf_type == SDF_TYPE_VOXELIZED {
            let local_pos = (color_obj.inverse_world * vec4<f32>(world_pos, 1.0)).xyz;
            let voxel_color = sample_voxelized_color(local_pos, color_obj);
            // White (1,1,1) = no tint. Any other color modulates albedo.
            if voxel_color.a > 0.01 {
                albedo = albedo * voxel_color.rgb;
            }
        }
    }
    var roughness = clamp(resolved.roughness, 0.04, 1.0);
    let metallic = resolved.metallic;

    // Procedural noise variation
    if resolved.noise_channels != 0u && resolved.noise_scale > 0.0 && resolved.noise_strength > 0.0 {
        let noise_pos = world_pos * resolved.noise_scale;
        let n = simplex3d(noise_pos);
        let ns = n * resolved.noise_strength;

        if (resolved.noise_channels & NOISE_CHANNEL_ALBEDO) != 0u {
            albedo = clamp(albedo + albedo * ns, vec3<f32>(0.0), vec3<f32>(1.0));
        }
        if (resolved.noise_channels & NOISE_CHANNEL_ROUGHNESS) != 0u {
            roughness = clamp(roughness + ns * 0.5, 0.04, 1.0);
        }
        if (resolved.noise_channels & NOISE_CHANNEL_NORMAL) != 0u {
            let eps = 0.01 / resolved.noise_scale;
            let dnx = simplex3d(noise_pos + vec3<f32>(eps, 0.0, 0.0)) - simplex3d(noise_pos - vec3<f32>(eps, 0.0, 0.0));
            let dny = simplex3d(noise_pos + vec3<f32>(0.0, eps, 0.0)) - simplex3d(noise_pos - vec3<f32>(0.0, eps, 0.0));
            let dnz = simplex3d(noise_pos + vec3<f32>(0.0, 0.0, eps)) - simplex3d(noise_pos - vec3<f32>(0.0, 0.0, eps));
            let bump = vec3<f32>(dnx, dny, dnz) * resolved.noise_strength * 0.5;
            normal = normalize(normal + bump);
        }
    }

    // F0: reflectance at normal incidence
    let f0 = mix(vec3<f32>(0.04), albedo, metallic);

    // View direction
    let view_dir = normalize(shade_uniforms.camera_pos.xyz - world_pos);
    let n_dot_v = max(dot(normal, view_dir), 0.001);

    let sss_color = resolved.subsurface_color;

    // Atmospheric shadow softening at distance
    let cam_dist = length(world_pos - shade_uniforms.camera_pos.xyz);
    let atmo_shadow_fill = (1.0 - exp(-SHADOW_ATMO_DENSITY * cam_dist)) * SHADOW_ATMO_MAX_FILL;

    // Per-pixel jitter to break cone tracing banding.
    let jitter = fract(sin(dot(vec2<f32>(pixel.xy), vec2<f32>(12.9898, 78.233))) * 43758.5453);

    // SDF junction contact shadow (gradient magnitude from ray marcher)
    let grad_mag = textureLoad(gbuf_motion, coord, 0).z;
    let contact = smoothstep(0.5, 0.8, grad_mag);

    let reflect_dir = reflect(-view_dir, normal);

    // Build ShadingContext
    let ctx = ShadingContext(
        world_pos,
        normal,
        view_dir,
        n_dot_v,
        albedo,
        roughness,
        metallic,
        resolved.emission,
        resolved.emission_strength,
        resolved.subsurface,
        resolved.subsurface_color,
        resolved.opacity,
        resolved.ior,
        f0,
        reflect_dir,
        cam_dist,
        jitter,
        contact,
        atmo_shadow_fill,
        pixel.xy,
        material_id,
        sss_color,
    );

    // Dispatch to shading model based on shader_id (from material table)
    let shader_id = materials[material_id].shader_id;
    var color = dispatch_shade(shader_id, ctx);

    // Debug visualization modes
    switch shade_uniforms.debug_mode {
        case 1u: {
            color = normal * 0.5 + 0.5;
        }
        case 2u: {
            color = abs(world_pos) * 0.5;
        }
        case 3u: {
            let mid = material_id;
            color = vec3<f32>(
                f32((mid * 7u + 3u) % 11u) / 10.0,
                f32((mid * 13u + 5u) % 11u) / 10.0,
                f32((mid * 19u + 7u) % 11u) / 10.0,
            );
        }
        case 4u: {
            // Diffuse-only: re-shade would be expensive, approximate
            color = ctx.albedo * (1.0 - ctx.metallic) * ctx.contact;
        }
        case 5u: {
            // Specular-only: approximate
            color = ctx.f0 * ctx.contact;
        }
        case 6u: {
            // GI only — indirect diffuse + specular, no direct lighting
            let ao = sdf_ao(ctx.world_pos + ctx.normal * SHADOW_BIAS, ctx.normal);
            let gi_origin = ctx.world_pos + ctx.normal * SHADOW_BIAS * 2.0;
            let gi_diffuse_raw = cone_trace_diffuse(gi_origin, ctx.normal, ctx.jitter);
            let kd_gi = (1.0 - ctx.metallic);
            let gi_diffuse = gi_diffuse_raw * ctx.albedo * kd_gi * ao * GI_STRENGTH;
            let gi_specular_raw = cone_trace_specular(gi_origin, ctx.reflect_dir, ctx.roughness, ctx.jitter);
            let gi_fresnel = fresnel_schlick(ctx.n_dot_v, ctx.f0);
            let gi_specular = gi_specular_raw * gi_fresnel * ao * GI_STRENGTH;
            color = (gi_diffuse + gi_specular) * ctx.contact;
        }
        case 7u: {
            // SDF distance visualization: blue (inside) → white (surface) → red (outside)
            let sdf_d = textureLoad(gbuf_motion, coord, 0).w;
            let scale = 10.0; // amplify small values for visibility
            let t7 = clamp(sdf_d * scale, -1.0, 1.0);
            if t7 < 0.0 {
                color = mix(vec3<f32>(1.0), vec3<f32>(0.0, 0.0, 1.0), -t7);
            } else {
                color = mix(vec3<f32>(1.0), vec3<f32>(1.0, 0.0, 0.0), t7);
            }
        }
        case 8u: {
            // Brick boundary overlay with hash-colored bricks and voxel sub-grid
            let obj_id = (packed_mat >> 24u) & 0xFFu;
            if obj_id > 0u {
                let obj = objects[obj_id - 1u];
                let local_pos = (obj.inverse_world * vec4<f32>(world_pos, 1.0)).xyz;
                let vs = obj.voxel_size;
                let grid_size = vec3<f32>(f32(obj.brick_map_dims_x), f32(obj.brick_map_dims_y), f32(obj.brick_map_dims_z)) * vs * 8.0;
                let grid_pos = local_pos + grid_size * 0.5;
                let voxel_coord = grid_pos / vs;
                let brick_coord = vec3<u32>(floor(voxel_coord / 8.0));
                let local_voxel = fract(voxel_coord / 8.0) * 8.0;

                // Brick boundary detection
                let edge_dist = min(local_voxel, vec3<f32>(8.0) - local_voxel);
                let min_edge = min(edge_dist.x, min(edge_dist.y, edge_dist.z));
                let on_brick_edge = 1.0 - smoothstep(0.2, 0.5, min_edge);

                // Voxel sub-grid (faint lines)
                let vf = fract(voxel_coord);
                let ve = min(vf, vec3<f32>(1.0) - vf);
                let on_voxel = (1.0 - smoothstep(0.1, 0.2, min(ve.x, min(ve.y, ve.z)))) * 0.2;

                // Hash brick coordinate for a unique color per brick
                let h = brick_coord.x * 73u + brick_coord.y * 157u + brick_coord.z * 311u;
                let bc = vec3<f32>(
                    f32((h * 13u + 7u) % 256u) / 255.0,
                    f32((h * 29u + 11u) % 256u) / 255.0,
                    f32((h * 43u + 17u) % 256u) / 255.0
                ) * 0.5 + 0.25;

                color = mix(bc, vec3<f32>(1.0, 1.0, 0.0), on_brick_edge);
                color = mix(color, vec3<f32>(0.6), on_voxel);
            } else {
                color = normal * 0.5 + 0.5; // fallback for non-objects
            }
        }
        default: {
            // Normal shading (already computed)
        }
    }

    textureStore(hdr_output, coord, vec4<f32>(color, 1.0));
}
