// Shading entry point — reads G-buffer, builds ShadingContext, dispatches
// to the appropriate shading model, handles debug visualization modes.
//
// This file is concatenated after shade_common.wgsl and all shading model
// files by the CPU-side ShaderComposer.

// ---------- Shader Dispatch ----------
// GENERATED BY SHADER_COMPOSER — do not edit this function manually.
// The ShaderComposer replaces the SHADER_DISPATCH_PLACEHOLDER marker below
// with a generated switch statement over all registered shading models.

// SHADER_DISPATCH_PLACEHOLDER

// ---------- Entry point ----------

@compute @workgroup_size(8, 8, 1)
fn main(@builtin(global_invocation_id) pixel: vec3<u32>) {
    let dims = vec2<u32>(textureDimensions(hdr_output));
    if pixel.x >= dims.x || pixel.y >= dims.y {
        return;
    }

    let coord = vec2<i32>(pixel.xy);

    // Read G-buffer
    let pos_data = textureLoad(gbuf_position, coord, 0);
    let hit_dist = pos_data.w;

    // Sky pixel — analytic atmosphere or fallback gradient.
    if hit_dist >= MAX_FLOAT * 0.5 {
        var sky: vec3<f32>;
        if shade_uniforms.sky_params.z > 0.5 {
            // Analytic Rayleigh + Mie atmosphere with sun disk.
            let ray_dir = compute_view_ray(pixel.xy, dims);
            sky = atmosphere_sky(ray_dir, normalize(shade_uniforms.sun_dir.xyz));
        } else {
            // Fallback: simple gradient.
            let uv_y = f32(pixel.y) / f32(dims.y);
            sky = mix(SKY_HORIZON, SKY_ZENITH, uv_y);
        }
        textureStore(hdr_output, coord, vec4<f32>(sky, 1.0));
        return;
    }

    let world_pos = pos_data.xyz;
    let normal_data = textureLoad(gbuf_normal, coord, 0);
    var normal = normalize(normal_data.xyz);

    let packed_mat = textureLoad(gbuf_material, coord, 0).r;
    let material_id = packed_mat & 0x3Fu;
    let secondary_id = (packed_mat >> 6u) & 0x3Fu;
    let blend_weight_u8 = (packed_mat >> 12u) & 0xFFu;
    let object_id_bits = (packed_mat >> 24u) & 0xFFu;

    // Resolve primary material from table.
    var resolved = resolve_material_from(materials[material_id]);

    // Material blending from G-buffer (sampled at exact hit point by ray march).
    let blend_weight = f32(blend_weight_u8) / 255.0;
    if blend_weight > 0.0 && secondary_id != material_id {
        let secondary = resolve_material_from(materials[secondary_id]);
        resolved = blend_resolved_materials(resolved, secondary, blend_weight);
    }

    // Per-voxel paint color from companion pool — intensity acts as paint alpha.
    if object_id_bits > 0u {
        for (var oi = 0u; oi < v2_scene.num_objects; oi = oi + 1u) {
            let obj = objects[oi];
            if obj.object_id == object_id_bits && obj.sdf_type == SDF_TYPE_VOXELIZED {
                let local_pos = (obj.inverse_world * vec4<f32>(world_pos, 1.0)).xyz;
                let paint = sample_voxelized_color(local_pos, obj);
                if paint.a > 0.0 {
                    resolved.albedo = mix(resolved.albedo, paint.rgb, paint.a);
                }
                break;
            }
        }
    }
    var albedo = resolved.albedo;
    var roughness = clamp(resolved.roughness, 0.04, 1.0);
    let metallic = resolved.metallic;

    // Procedural noise variation
    if resolved.noise_channels != 0u && resolved.noise_scale > 0.0 && resolved.noise_strength > 0.0 {
        let noise_pos = world_pos * resolved.noise_scale;
        let n = simplex3d(noise_pos);
        let ns = n * resolved.noise_strength;

        if (resolved.noise_channels & NOISE_CHANNEL_ALBEDO) != 0u {
            albedo = clamp(albedo + albedo * ns, vec3<f32>(0.0), vec3<f32>(1.0));
        }
        if (resolved.noise_channels & NOISE_CHANNEL_ROUGHNESS) != 0u {
            roughness = clamp(roughness + ns * 0.5, 0.04, 1.0);
        }
        if (resolved.noise_channels & NOISE_CHANNEL_NORMAL) != 0u {
            let eps = 0.01 / resolved.noise_scale;
            let dnx = simplex3d(noise_pos + vec3<f32>(eps, 0.0, 0.0)) - simplex3d(noise_pos - vec3<f32>(eps, 0.0, 0.0));
            let dny = simplex3d(noise_pos + vec3<f32>(0.0, eps, 0.0)) - simplex3d(noise_pos - vec3<f32>(0.0, eps, 0.0));
            let dnz = simplex3d(noise_pos + vec3<f32>(0.0, 0.0, eps)) - simplex3d(noise_pos - vec3<f32>(0.0, 0.0, eps));
            let bump = vec3<f32>(dnx, dny, dnz) * resolved.noise_strength * 0.5;
            normal = normalize(normal + bump);
        }
    }

    // F0: reflectance at normal incidence
    let f0 = mix(vec3<f32>(0.04), albedo, metallic);

    // View direction
    let view_dir = normalize(shade_uniforms.camera_pos.xyz - world_pos);
    let n_dot_v = max(dot(normal, view_dir), 0.001);

    // Use the per-voxel albedo (which includes voxel color) for SSS,
    // not the material's subsurface_color. Otherwise changing materials
    // overwrites the visual color via SSS contribution.
    let sss_color = albedo;

    // Atmospheric shadow softening at distance
    let cam_dist = length(world_pos - shade_uniforms.camera_pos.xyz);
    let atmo_shadow_fill = (1.0 - exp(-SHADOW_ATMO_DENSITY * cam_dist)) * SHADOW_ATMO_MAX_FILL;

    // Per-pixel jitter to break cone tracing banding.
    let jitter = fract(sin(dot(vec2<f32>(pixel.xy), vec2<f32>(12.9898, 78.233))) * 43758.5453);

    // SDF junction contact shadow (gradient magnitude from ray marcher)
    let grad_mag = textureLoad(gbuf_motion, coord, 0).z;
    let contact = smoothstep(0.5, 0.8, grad_mag);

    let reflect_dir = reflect(-view_dir, normal);

    // Build ShadingContext
    let ctx = ShadingContext(
        world_pos,
        normal,
        view_dir,
        n_dot_v,
        albedo,
        roughness,
        metallic,
        resolved.emission,
        resolved.emission_strength,
        resolved.subsurface,
        resolved.subsurface_color,
        resolved.opacity,
        resolved.ior,
        f0,
        reflect_dir,
        cam_dist,
        jitter,
        contact,
        atmo_shadow_fill,
        pixel.xy,
        material_id,
        sss_color,
    );

    // Dispatch to shading model based on shader_id (from material table)
    let shader_id = materials[material_id].shader_id;
    var color = dispatch_shade(shader_id, ctx);

    // Debug visualization modes
    switch shade_uniforms.debug_mode {
        case 1u: {
            color = normal * 0.5 + 0.5;
        }
        case 2u: {
            color = abs(world_pos) * 0.5;
        }
        case 3u: {
            let mid = material_id;
            color = vec3<f32>(
                f32((mid * 7u + 3u) % 11u) / 10.0,
                f32((mid * 13u + 5u) % 11u) / 10.0,
                f32((mid * 19u + 7u) % 11u) / 10.0,
            );
        }
        case 4u: {
            // Diffuse-only: re-shade would be expensive, approximate
            color = ctx.albedo * (1.0 - ctx.metallic) * ctx.contact;
        }
        case 5u: {
            // Specular-only: approximate
            color = ctx.f0 * ctx.contact;
        }
        case 6u: {
            // GI only — indirect diffuse + specular, no direct lighting
            let ao = sdf_ao(ctx.world_pos + ctx.normal * SHADOW_BIAS, ctx.normal);
            let gi_origin = ctx.world_pos + ctx.normal * SHADOW_BIAS * 2.0;
            let gi_diffuse_raw = cone_trace_diffuse(gi_origin, ctx.normal, ctx.jitter);
            let kd_gi = (1.0 - ctx.metallic);
            let gi_diffuse = gi_diffuse_raw * ctx.albedo * kd_gi * ao * shade_uniforms.sun_color.w;
            let gi_specular_raw = cone_trace_specular(gi_origin, ctx.reflect_dir, ctx.roughness, ctx.jitter);
            let gi_fresnel = fresnel_schlick(ctx.n_dot_v, ctx.f0);
            let gi_specular = gi_specular_raw * gi_fresnel * ao * shade_uniforms.sun_color.w;
            color = (gi_diffuse + gi_specular) * ctx.contact;
        }
        case 7u: {
            // SDF distance visualization: blue (inside) → white (surface) → red (outside)
            let sdf_d = textureLoad(gbuf_motion, coord, 0).w;
            let scale = 10.0; // amplify small values for visibility
            let t7 = clamp(sdf_d * scale, -1.0, 1.0);
            if t7 < 0.0 {
                color = mix(vec3<f32>(1.0), vec3<f32>(0.0, 0.0, 1.0), -t7);
            } else {
                color = mix(vec3<f32>(1.0), vec3<f32>(1.0, 0.0, 0.0), t7);
            }
        }
        case 8u: {
            // Brick boundary overlay with hash-colored bricks and voxel sub-grid
            let obj_id8 = (packed_mat >> 24u) & 0xFFu;
            var found_obj8 = false;
            var obj8_idx = 0u;
            for (var oi8 = 0u; oi8 < v2_scene.num_objects; oi8 = oi8 + 1u) {
                if objects[oi8].object_id == obj_id8 {
                    obj8_idx = oi8;
                    found_obj8 = true;
                    break;
                }
            }
            if found_obj8 {
                let obj = objects[obj8_idx];
                let local_pos = (obj.inverse_world * vec4<f32>(world_pos, 1.0)).xyz;
                let vs = obj.voxel_size;
                let grid_size = vec3<f32>(f32(obj.brick_map_dims_x), f32(obj.brick_map_dims_y), f32(obj.brick_map_dims_z)) * vs * 8.0;
                let grid_pos = local_pos + grid_size * 0.5;
                let voxel_coord = grid_pos / vs;
                let brick_coord = vec3<u32>(floor(voxel_coord / 8.0));
                let local_voxel = fract(voxel_coord / 8.0) * 8.0;

                // Brick boundary detection
                let edge_dist = min(local_voxel, vec3<f32>(8.0) - local_voxel);
                let min_edge = min(edge_dist.x, min(edge_dist.y, edge_dist.z));
                let on_brick_edge = 1.0 - smoothstep(0.2, 0.5, min_edge);

                // Voxel sub-grid (faint lines)
                let vf = fract(voxel_coord);
                let ve = min(vf, vec3<f32>(1.0) - vf);
                let on_voxel = (1.0 - smoothstep(0.1, 0.2, min(ve.x, min(ve.y, ve.z)))) * 0.2;

                // Hash brick coordinate for a unique color per brick
                let h = brick_coord.x * 73u + brick_coord.y * 157u + brick_coord.z * 311u;
                let bc = vec3<f32>(
                    f32((h * 13u + 7u) % 256u) / 255.0,
                    f32((h * 29u + 11u) % 256u) / 255.0,
                    f32((h * 43u + 17u) % 256u) / 255.0
                ) * 0.5 + 0.25;

                color = mix(bc, vec3<f32>(1.0, 1.0, 0.0), on_brick_edge);
                color = mix(color, vec3<f32>(0.6), on_voxel);
            } else {
                color = normal * 0.5 + 0.5; // fallback for non-objects
            }
        }
        default: {
            // Normal shading (already computed)
        }
    }

    // Brush overlay cursor ring — Euclidean distance from brush center in local space.
    // The G-buffer only contains surface pixels, so the ring naturally clips at edges.
    if brush_overlay.brush_active != 0u && object_id_bits > 0u {
        for (var oi_b = 0u; oi_b < v2_scene.num_objects; oi_b = oi_b + 1u) {
            let obj_b = objects[oi_b];
            if obj_b.object_id == brush_overlay.brush_object_id && obj_b.sdf_type == SDF_TYPE_VOXELIZED {
                let local_pos_b = (obj_b.inverse_world * vec4<f32>(world_pos, 1.0)).xyz;
                let diff = local_pos_b - brush_overlay.brush_center_local.xyz;
                // Scale-aware distance (account for non-uniform object scale).
                let scale = vec3<f32>(obj_b.accumulated_scale_x, obj_b.accumulated_scale_y, obj_b.accumulated_scale_z);
                let dist = length(diff * scale);

                let radius = brush_overlay.brush_radius;
                let falloff_frac = brush_overlay.brush_falloff;

                // Only draw within a reasonable range of the brush.
                if dist < radius * 1.5 {
                    // Outer ring: at brush_radius
                    let ring_width = radius * 0.04;
                    let outer_t = abs(dist - radius) / ring_width;
                    let outer_ring = 1.0 - smoothstep(0.0, 1.0, outer_t);

                    // Inner ring: at core radius (falloff boundary)
                    var inner_ring = 0.0;
                    if falloff_frac > 0.01 {
                        let core_radius = radius * (1.0 - falloff_frac);
                        let inner_t = abs(dist - core_radius) / ring_width;
                        inner_ring = (1.0 - smoothstep(0.0, 1.0, inner_t)) * 0.4;
                    }

                    let ring_alpha = max(outer_ring, inner_ring);
                    if ring_alpha > 0.01 {
                        let ring_col = brush_overlay.brush_color.rgb;
                        color = mix(color, ring_col, ring_alpha * brush_overlay.brush_color.a);
                    }
                }
                break;
            }
        }
    }

    textureStore(hdr_output, coord, vec4<f32>(color, 1.0));
}
