//! Gameplay registry — central catalog of registered components, systems, and blueprints.
//!
//! Both engine components (registered at startup via `engine_register()`) and gameplay
//! components (registered by the dylib's `register()`) populate the same registry.

use super::game_value::GameValue;
use std::collections::HashMap;

// ─── Field introspection ──────────────────────────────────────────────────

/// Type of a component field, used for inspector rendering and MCP tools.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FieldType {
    /// `f32` or `f64`.
    Float,
    /// `i32` or `i64`.
    Int,
    /// `bool`.
    Bool,
    /// `Vec3` (direction, offset — not a position).
    Vec3,
    /// `WorldPosition` (full-precision world position).
    WorldPosition,
    /// `Quat` (rotation).
    Quat,
    /// `String`.
    String,
    /// `hecs::Entity` (entity reference).
    Entity,
    /// Enum type (rendered as dropdown).
    Enum,
    /// `Vec<T>` or other list type.
    List,
    /// `[f32; 4]` RGBA color.
    Color,
}

/// Metadata for a single field on a component.
#[derive(Debug, Clone)]
pub struct FieldMeta {
    /// Field name (matches the Rust struct field name).
    pub name: &'static str,
    /// Type classification for rendering.
    pub field_type: FieldType,
    /// True if the field is `#[serde(skip)]` — transient runtime state.
    pub transient: bool,
    /// Optional numeric range for slider display `(min, max)`.
    pub range: Option<(f64, f64)>,
    /// Optional default value for display in the inspector.
    pub default: Option<GameValue>,
}

/// Trait for component field introspection.
///
/// Generated by the `#[component]` attribute macro. Provides the inspector,
/// MCP tools, and future JS bindings with field-level metadata.
pub trait ComponentMeta {
    /// The component's type name (e.g., `"Health"`, `"Patrol"`).
    fn type_name() -> &'static str;
    /// Field metadata for all non-transient fields.
    fn fields() -> &'static [FieldMeta];
}

// ─── Type-erased component operations ─────────────────────────────────────

/// Type-erased operations for a component type, stored in the [`GameplayRegistry`].
///
/// These function pointers are generated by the `#[component]` macro and live
/// in the dylib. They become invalid when the dylib is unloaded — the hot-reload
/// cycle serializes components before unload and deserializes after load.
pub struct ComponentEntry {
    /// Stable string name (from `ComponentMeta::type_name()`).
    pub name: &'static str,
    /// Serialize the component on `entity` to RON. Returns `None` if entity lacks this component.
    /// Entity references are remapped to StableId UUIDs.
    pub serialize: fn(&hecs::World, hecs::Entity) -> Option<String>,
    /// Deserialize a component from RON and insert it on `entity`.
    /// StableId UUIDs in Entity fields are resolved to live handles.
    pub deserialize_insert:
        fn(&mut hecs::World, hecs::Entity, &str) -> Result<(), String>,
    /// Remove this component from `entity` (runs drop in the correct dylib).
    pub remove: fn(&mut hecs::World, hecs::Entity),
    /// Check whether `entity` has this component.
    pub has: fn(&hecs::World, hecs::Entity) -> bool,
    /// Read a single field by name as a `GameValue`.
    pub get_field:
        fn(&hecs::World, hecs::Entity, &str) -> Result<GameValue, String>,
    /// Write a single field by name from a `GameValue`.
    pub set_field:
        fn(&mut hecs::World, hecs::Entity, &str, GameValue) -> Result<(), String>,
    /// Field metadata (same as `ComponentMeta::fields()`).
    pub meta: &'static [FieldMeta],
}

// Debug can't auto-derive due to fn pointers, so implement manually.
impl std::fmt::Debug for ComponentEntry {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ComponentEntry")
            .field("name", &self.name)
            .field("meta", &self.meta)
            .finish_non_exhaustive()
    }
}

// ─── System metadata ──────────────────────────────────────────────────────

/// Execution phase for systems.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Phase {
    /// General gameplay: AI, movement, interactions, game logic.
    Update,
    /// Runs after Update: camera follow, UI sync, cleanup.
    LateUpdate,
}

/// Metadata for a registered system, collected via `inventory`.
pub struct SystemMeta {
    /// Function name (e.g., `"patrol_system"`).
    pub name: &'static str,
    /// Module path for disambiguation (e.g., `"ai::patrol_system"`).
    pub module_path: &'static str,
    /// Which phase this system runs in.
    pub phase: Phase,
    /// Systems that must run before this one (full function names).
    pub after: &'static [&'static str],
    /// Systems that must run after this one (full function names).
    pub before: &'static [&'static str],
    /// The system function pointer. Called by the scheduler.
    /// The actual type is `fn(&mut SystemContext)` but stored as raw pointer
    /// to avoid circular dependency on SystemContext definition.
    pub fn_ptr: *const (),
}

// Safety: SystemMeta is only constructed from static data and fn pointers.
unsafe impl Send for SystemMeta {}
unsafe impl Sync for SystemMeta {}

impl std::fmt::Debug for SystemMeta {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SystemMeta")
            .field("name", &self.name)
            .field("module_path", &self.module_path)
            .field("phase", &self.phase)
            .field("after", &self.after)
            .field("before", &self.before)
            .finish_non_exhaustive()
    }
}

// ─── Query error ──────────────────────────────────────────────────────────

/// Error returned by `find_one` when the query doesn't match exactly one entity.
#[derive(Debug, Clone, thiserror::Error)]
pub enum QueryError {
    /// No entity matches the query.
    #[error("no entity found matching query")]
    NotFound,
    /// Multiple entities match — the query is ambiguous.
    #[error("multiple entities found matching query (expected exactly one)")]
    Multiple,
}

// ─── Gameplay registry ────────────────────────────────────────────────────

/// Central registry of all known components, systems, and blueprints.
///
/// Populated in two stages:
/// 1. `engine_register()` — engine components from the static binary (before dylib loads)
/// 2. `register()` — gameplay components from the game dylib (after dylib loads)
///
/// Both use `inventory` for auto-discovery. The inspector, MCP tools, and
/// scene serialization treat engine and gameplay components identically.
pub struct GameplayRegistry {
    components: HashMap<String, ComponentEntry>,
    systems: Vec<SystemMeta>,
    // blueprints: HashMap<String, Blueprint>,  // added in Phase 11
}

impl Default for GameplayRegistry {
    fn default() -> Self {
        Self::new()
    }
}

impl GameplayRegistry {
    /// Create an empty registry.
    pub fn new() -> Self {
        Self {
            components: HashMap::new(),
            systems: Vec::new(),
        }
    }

    /// Register a component type. Returns error if a component with the same name
    /// is already registered.
    pub fn register_component(&mut self, entry: ComponentEntry) -> Result<(), String> {
        if self.components.contains_key(entry.name) {
            return Err(format!(
                "duplicate component registration: '{}'",
                entry.name
            ));
        }
        self.components.insert(entry.name.to_owned(), entry);
        Ok(())
    }

    /// Register a system. Duplicate names are allowed at registration time —
    /// the scheduler detects and reports ambiguities when building the dependency graph.
    pub fn register_system(&mut self, meta: SystemMeta) {
        self.systems.push(meta);
    }

    /// Collect all `inventory`-registered components and systems.
    ///
    /// Called by the dylib's `register()` function and by `engine_register()`.
    /// This is a convenience that gathers everything `inventory` knows about.
    // Note: actual inventory collection requires the component/system types
    // to submit to inventory, which the #[component] and #[system] macros do.
    // For now this is a placeholder — the macro implementation will populate it.
    pub fn collect_all(&mut self) {
        // Will be implemented when #[component] and #[system] macros generate
        // inventory::submit! calls. For now, manual registration via
        // register_component() and register_system() works.
    }

    /// Remove all gameplay entries (keeping engine entries).
    ///
    /// Called during hot-reload before loading the new dylib.
    /// Engine components (registered via `engine_register()`) are not removed.
    ///
    /// Implementation: tracks which entries are engine vs gameplay.
    /// For now, clears everything — Phase 9 will add engine/gameplay distinction.
    pub fn clear_gameplay(&mut self) {
        self.components.clear();
        self.systems.clear();
    }

    // ─── Queries ──────────────────────────────────────────────────────────

    /// Look up a component entry by name.
    pub fn component_entry(&self, name: &str) -> Option<&ComponentEntry> {
        self.components.get(name)
    }

    /// List all registered component names.
    pub fn component_names(&self) -> impl Iterator<Item = &str> {
        self.components.keys().map(|s| s.as_str())
    }

    /// Number of registered components.
    pub fn component_count(&self) -> usize {
        self.components.len()
    }

    /// List all registered systems.
    pub fn system_list(&self) -> &[SystemMeta] {
        &self.systems
    }

    /// Check whether a component with the given name is registered.
    pub fn has_component(&self, name: &str) -> bool {
        self.components.contains_key(name)
    }

    /// Iterate over all component entries.
    pub fn component_entries(&self) -> impl Iterator<Item = &ComponentEntry> {
        self.components.values()
    }
}

impl std::fmt::Debug for GameplayRegistry {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("GameplayRegistry")
            .field("components", &self.components.keys().collect::<Vec<_>>())
            .field("systems", &self.systems.len())
            .finish()
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // Helper: create a dummy ComponentEntry for testing.
    fn dummy_entry(name: &'static str) -> ComponentEntry {
        ComponentEntry {
            name,
            serialize: |_, _| None,
            deserialize_insert: |_, _, _| Ok(()),
            remove: |_, _| {},
            has: |_, _| false,
            get_field: |_, _, _| Err("stub".into()),
            set_field: |_, _, _, _| Err("stub".into()),
            meta: &[],
        }
    }

    #[test]
    fn register_and_query_component() {
        let mut reg = GameplayRegistry::new();
        reg.register_component(dummy_entry("Health")).unwrap();
        reg.register_component(dummy_entry("Patrol")).unwrap();

        assert_eq!(reg.component_count(), 2);
        assert!(reg.has_component("Health"));
        assert!(reg.has_component("Patrol"));
        assert!(!reg.has_component("Missing"));

        let entry = reg.component_entry("Health").unwrap();
        assert_eq!(entry.name, "Health");
    }

    #[test]
    fn duplicate_component_name_rejected() {
        let mut reg = GameplayRegistry::new();
        reg.register_component(dummy_entry("Health")).unwrap();
        let err = reg.register_component(dummy_entry("Health")).unwrap_err();
        assert!(err.contains("duplicate"));
    }

    #[test]
    fn register_system() {
        let mut reg = GameplayRegistry::new();
        reg.register_system(SystemMeta {
            name: "patrol_system",
            module_path: "systems::patrol_system",
            phase: Phase::Update,
            after: &[],
            before: &[],
            fn_ptr: std::ptr::null(),
        });
        assert_eq!(reg.system_list().len(), 1);
        assert_eq!(reg.system_list()[0].name, "patrol_system");
        assert_eq!(reg.system_list()[0].phase, Phase::Update);
    }

    #[test]
    fn component_names_iteration() {
        let mut reg = GameplayRegistry::new();
        reg.register_component(dummy_entry("A")).unwrap();
        reg.register_component(dummy_entry("B")).unwrap();
        reg.register_component(dummy_entry("C")).unwrap();

        let mut names: Vec<_> = reg.component_names().collect();
        names.sort();
        assert_eq!(names, vec!["A", "B", "C"]);
    }

    #[test]
    fn clear_gameplay_removes_all() {
        let mut reg = GameplayRegistry::new();
        reg.register_component(dummy_entry("Health")).unwrap();
        reg.register_system(SystemMeta {
            name: "test",
            module_path: "test",
            phase: Phase::Update,
            after: &[],
            before: &[],
            fn_ptr: std::ptr::null(),
        });

        reg.clear_gameplay();
        assert_eq!(reg.component_count(), 0);
        assert!(reg.system_list().is_empty());
    }

    #[test]
    fn field_meta_construction() {
        let meta = FieldMeta {
            name: "health",
            field_type: FieldType::Float,
            transient: false,
            range: Some((0.0, 100.0)),
            default: Some(GameValue::Float(100.0)),
        };
        assert_eq!(meta.name, "health");
        assert_eq!(meta.field_type, FieldType::Float);
        assert!(!meta.transient);
        assert_eq!(meta.range, Some((0.0, 100.0)));
    }

    #[test]
    fn phase_equality() {
        assert_eq!(Phase::Update, Phase::Update);
        assert_ne!(Phase::Update, Phase::LateUpdate);
    }

    #[test]
    fn query_error_display() {
        let e = QueryError::NotFound;
        assert!(format!("{}", e).contains("no entity found"));

        let e = QueryError::Multiple;
        assert!(format!("{}", e).contains("multiple entities"));
    }
}
